// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: client.proto

#include "client.pb.h"
#include "client.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace protocol {
namespace ncx_client {

static const char* ConfigInfo_method_names[] = {
  "/protocol.ncx_client.ConfigInfo/AskConfigInfo",
};

std::unique_ptr< ConfigInfo::Stub> ConfigInfo::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ConfigInfo::Stub> stub(new ConfigInfo::Stub(channel, options));
  return stub;
}

ConfigInfo::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AskConfigInfo_(ConfigInfo_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ConfigInfo::Stub::AskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::protocol::ncx_client::ConfigInfoResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protocol::ncx_client::ConfigInfoReq, ::protocol::ncx_client::ConfigInfoResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AskConfigInfo_, context, request, response);
}

void ConfigInfo::Stub::async::AskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq* request, ::protocol::ncx_client::ConfigInfoResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protocol::ncx_client::ConfigInfoReq, ::protocol::ncx_client::ConfigInfoResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AskConfigInfo_, context, request, response, std::move(f));
}

void ConfigInfo::Stub::async::AskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq* request, ::protocol::ncx_client::ConfigInfoResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AskConfigInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protocol::ncx_client::ConfigInfoResp>* ConfigInfo::Stub::PrepareAsyncAskConfigInfoRaw(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protocol::ncx_client::ConfigInfoResp, ::protocol::ncx_client::ConfigInfoReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AskConfigInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protocol::ncx_client::ConfigInfoResp>* ConfigInfo::Stub::AsyncAskConfigInfoRaw(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAskConfigInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

ConfigInfo::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConfigInfo_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConfigInfo::Service, ::protocol::ncx_client::ConfigInfoReq, ::protocol::ncx_client::ConfigInfoResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConfigInfo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protocol::ncx_client::ConfigInfoReq* req,
             ::protocol::ncx_client::ConfigInfoResp* resp) {
               return service->AskConfigInfo(ctx, req, resp);
             }, this)));
}

ConfigInfo::Service::~Service() {
}

::grpc::Status ConfigInfo::Service::AskConfigInfo(::grpc::ServerContext* context, const ::protocol::ncx_client::ConfigInfoReq* request, ::protocol::ncx_client::ConfigInfoResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace protocol
}  // namespace ncx_client

