// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: client.proto
// Original file comments:
// Web后台与NCX客户端的rpc通信协议
//
#ifndef GRPC_client_2eproto__INCLUDED
#define GRPC_client_2eproto__INCLUDED

#include "client.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace protocol {
namespace ncx_client {

// 配置信息服务
class ConfigInfo final {
 public:
  static constexpr char const* service_full_name() {
    return "protocol.ncx_client.ConfigInfo";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 获取配置信息
    virtual ::grpc::Status AskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::protocol::ncx_client::ConfigInfoResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::ncx_client::ConfigInfoResp>> AsyncAskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::ncx_client::ConfigInfoResp>>(AsyncAskConfigInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::ncx_client::ConfigInfoResp>> PrepareAsyncAskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::ncx_client::ConfigInfoResp>>(PrepareAsyncAskConfigInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 获取配置信息
      virtual void AskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq* request, ::protocol::ncx_client::ConfigInfoResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq* request, ::protocol::ncx_client::ConfigInfoResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protocol::ncx_client::ConfigInfoResp>* AsyncAskConfigInfoRaw(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protocol::ncx_client::ConfigInfoResp>* PrepareAsyncAskConfigInfoRaw(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::protocol::ncx_client::ConfigInfoResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::ncx_client::ConfigInfoResp>> AsyncAskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::ncx_client::ConfigInfoResp>>(AsyncAskConfigInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::ncx_client::ConfigInfoResp>> PrepareAsyncAskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::ncx_client::ConfigInfoResp>>(PrepareAsyncAskConfigInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq* request, ::protocol::ncx_client::ConfigInfoResp* response, std::function<void(::grpc::Status)>) override;
      void AskConfigInfo(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq* request, ::protocol::ncx_client::ConfigInfoResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::protocol::ncx_client::ConfigInfoResp>* AsyncAskConfigInfoRaw(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::protocol::ncx_client::ConfigInfoResp>* PrepareAsyncAskConfigInfoRaw(::grpc::ClientContext* context, const ::protocol::ncx_client::ConfigInfoReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AskConfigInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 获取配置信息
    virtual ::grpc::Status AskConfigInfo(::grpc::ServerContext* context, const ::protocol::ncx_client::ConfigInfoReq* request, ::protocol::ncx_client::ConfigInfoResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AskConfigInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AskConfigInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AskConfigInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskConfigInfo(::grpc::ServerContext* /*context*/, const ::protocol::ncx_client::ConfigInfoReq* /*request*/, ::protocol::ncx_client::ConfigInfoResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAskConfigInfo(::grpc::ServerContext* context, ::protocol::ncx_client::ConfigInfoReq* request, ::grpc::ServerAsyncResponseWriter< ::protocol::ncx_client::ConfigInfoResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AskConfigInfo<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AskConfigInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AskConfigInfo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::protocol::ncx_client::ConfigInfoReq, ::protocol::ncx_client::ConfigInfoResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::protocol::ncx_client::ConfigInfoReq* request, ::protocol::ncx_client::ConfigInfoResp* response) { return this->AskConfigInfo(context, request, response); }));}
    void SetMessageAllocatorFor_AskConfigInfo(
        ::grpc::MessageAllocator< ::protocol::ncx_client::ConfigInfoReq, ::protocol::ncx_client::ConfigInfoResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::protocol::ncx_client::ConfigInfoReq, ::protocol::ncx_client::ConfigInfoResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AskConfigInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskConfigInfo(::grpc::ServerContext* /*context*/, const ::protocol::ncx_client::ConfigInfoReq* /*request*/, ::protocol::ncx_client::ConfigInfoResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AskConfigInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::protocol::ncx_client::ConfigInfoReq* /*request*/, ::protocol::ncx_client::ConfigInfoResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AskConfigInfo<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AskConfigInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AskConfigInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AskConfigInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskConfigInfo(::grpc::ServerContext* /*context*/, const ::protocol::ncx_client::ConfigInfoReq* /*request*/, ::protocol::ncx_client::ConfigInfoResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AskConfigInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AskConfigInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AskConfigInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskConfigInfo(::grpc::ServerContext* /*context*/, const ::protocol::ncx_client::ConfigInfoReq* /*request*/, ::protocol::ncx_client::ConfigInfoResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAskConfigInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AskConfigInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AskConfigInfo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AskConfigInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_AskConfigInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskConfigInfo(::grpc::ServerContext* /*context*/, const ::protocol::ncx_client::ConfigInfoReq* /*request*/, ::protocol::ncx_client::ConfigInfoResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AskConfigInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AskConfigInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AskConfigInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::protocol::ncx_client::ConfigInfoReq, ::protocol::ncx_client::ConfigInfoResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::protocol::ncx_client::ConfigInfoReq, ::protocol::ncx_client::ConfigInfoResp>* streamer) {
                       return this->StreamedAskConfigInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AskConfigInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AskConfigInfo(::grpc::ServerContext* /*context*/, const ::protocol::ncx_client::ConfigInfoReq* /*request*/, ::protocol::ncx_client::ConfigInfoResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAskConfigInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::protocol::ncx_client::ConfigInfoReq,::protocol::ncx_client::ConfigInfoResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AskConfigInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AskConfigInfo<Service > StreamedService;
};

}  // namespace ncx_client
}  // namespace protocol


#endif  // GRPC_client_2eproto__INCLUDED
