// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protocol_2eproto;
namespace protocol {
class ControlChannelCmd;
class ControlChannelCmdDefaultTypeInternal;
extern ControlChannelCmdDefaultTypeInternal _ControlChannelCmd_default_instance_;
class DataChannelCmd;
class DataChannelCmdDefaultTypeInternal;
extern DataChannelCmdDefaultTypeInternal _DataChannelCmd_default_instance_;
class Hello;
class HelloDefaultTypeInternal;
extern HelloDefaultTypeInternal _Hello_default_instance_;
}  // namespace protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::protocol::ControlChannelCmd* Arena::CreateMaybeMessage<::protocol::ControlChannelCmd>(Arena*);
template<> ::protocol::DataChannelCmd* Arena::CreateMaybeMessage<::protocol::DataChannelCmd>(Arena*);
template<> ::protocol::Hello* Arena::CreateMaybeMessage<::protocol::Hello>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protocol {

enum ControlChannelCmd_CCmd : int {
  ControlChannelCmd_CCmd_CREATE_DATA_CHANNEL = 0,
  ControlChannelCmd_CCmd_HEARTBEAT = 1,
  ControlChannelCmd_CCmd_ControlChannelCmd_CCmd_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ControlChannelCmd_CCmd_ControlChannelCmd_CCmd_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ControlChannelCmd_CCmd_IsValid(int value);
constexpr ControlChannelCmd_CCmd ControlChannelCmd_CCmd_CCmd_MIN = ControlChannelCmd_CCmd_CREATE_DATA_CHANNEL;
constexpr ControlChannelCmd_CCmd ControlChannelCmd_CCmd_CCmd_MAX = ControlChannelCmd_CCmd_HEARTBEAT;
constexpr int ControlChannelCmd_CCmd_CCmd_ARRAYSIZE = ControlChannelCmd_CCmd_CCmd_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ControlChannelCmd_CCmd_descriptor();
template<typename T>
inline const std::string& ControlChannelCmd_CCmd_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ControlChannelCmd_CCmd>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ControlChannelCmd_CCmd_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ControlChannelCmd_CCmd_descriptor(), enum_t_value);
}
inline bool ControlChannelCmd_CCmd_Parse(
    const std::string& name, ControlChannelCmd_CCmd* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ControlChannelCmd_CCmd>(
    ControlChannelCmd_CCmd_descriptor(), name, value);
}
enum DataChannelCmd_DCmd : int {
  DataChannelCmd_DCmd_START_FORWARD_TCP = 0,
  DataChannelCmd_DCmd_START_FORWARD_UDP = 1,
  DataChannelCmd_DCmd_DataChannelCmd_DCmd_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  DataChannelCmd_DCmd_DataChannelCmd_DCmd_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool DataChannelCmd_DCmd_IsValid(int value);
constexpr DataChannelCmd_DCmd DataChannelCmd_DCmd_DCmd_MIN = DataChannelCmd_DCmd_START_FORWARD_TCP;
constexpr DataChannelCmd_DCmd DataChannelCmd_DCmd_DCmd_MAX = DataChannelCmd_DCmd_START_FORWARD_UDP;
constexpr int DataChannelCmd_DCmd_DCmd_ARRAYSIZE = DataChannelCmd_DCmd_DCmd_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DataChannelCmd_DCmd_descriptor();
template<typename T>
inline const std::string& DataChannelCmd_DCmd_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DataChannelCmd_DCmd>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DataChannelCmd_DCmd_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DataChannelCmd_DCmd_descriptor(), enum_t_value);
}
inline bool DataChannelCmd_DCmd_Parse(
    const std::string& name, DataChannelCmd_DCmd* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DataChannelCmd_DCmd>(
    DataChannelCmd_DCmd_descriptor(), name, value);
}
enum Hello_HelloType : int {
  Hello_HelloType_CONTROL_CHANNEL_HELLO = 0,
  Hello_HelloType_DATA_CHANNEL_HELLO = 1,
  Hello_HelloType_Hello_HelloType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Hello_HelloType_Hello_HelloType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Hello_HelloType_IsValid(int value);
constexpr Hello_HelloType Hello_HelloType_HelloType_MIN = Hello_HelloType_CONTROL_CHANNEL_HELLO;
constexpr Hello_HelloType Hello_HelloType_HelloType_MAX = Hello_HelloType_DATA_CHANNEL_HELLO;
constexpr int Hello_HelloType_HelloType_ARRAYSIZE = Hello_HelloType_HelloType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Hello_HelloType_descriptor();
template<typename T>
inline const std::string& Hello_HelloType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Hello_HelloType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Hello_HelloType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Hello_HelloType_descriptor(), enum_t_value);
}
inline bool Hello_HelloType_Parse(
    const std::string& name, Hello_HelloType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Hello_HelloType>(
    Hello_HelloType_descriptor(), name, value);
}
// ===================================================================

class ControlChannelCmd PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.ControlChannelCmd) */ {
 public:
  inline ControlChannelCmd() : ControlChannelCmd(nullptr) {};
  virtual ~ControlChannelCmd();

  ControlChannelCmd(const ControlChannelCmd& from);
  ControlChannelCmd(ControlChannelCmd&& from) noexcept
    : ControlChannelCmd() {
    *this = ::std::move(from);
  }

  inline ControlChannelCmd& operator=(const ControlChannelCmd& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlChannelCmd& operator=(ControlChannelCmd&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ControlChannelCmd& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ControlChannelCmd* internal_default_instance() {
    return reinterpret_cast<const ControlChannelCmd*>(
               &_ControlChannelCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ControlChannelCmd& a, ControlChannelCmd& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlChannelCmd* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlChannelCmd* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ControlChannelCmd* New() const final {
    return CreateMaybeMessage<ControlChannelCmd>(nullptr);
  }

  ControlChannelCmd* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ControlChannelCmd>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ControlChannelCmd& from);
  void MergeFrom(const ControlChannelCmd& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ControlChannelCmd* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.ControlChannelCmd";
  }
  protected:
  explicit ControlChannelCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protocol_2eproto);
    return ::descriptor_table_protocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef ControlChannelCmd_CCmd CCmd;
  static constexpr CCmd CREATE_DATA_CHANNEL =
    ControlChannelCmd_CCmd_CREATE_DATA_CHANNEL;
  static constexpr CCmd HEARTBEAT =
    ControlChannelCmd_CCmd_HEARTBEAT;
  static inline bool CCmd_IsValid(int value) {
    return ControlChannelCmd_CCmd_IsValid(value);
  }
  static constexpr CCmd CCmd_MIN =
    ControlChannelCmd_CCmd_CCmd_MIN;
  static constexpr CCmd CCmd_MAX =
    ControlChannelCmd_CCmd_CCmd_MAX;
  static constexpr int CCmd_ARRAYSIZE =
    ControlChannelCmd_CCmd_CCmd_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  CCmd_descriptor() {
    return ControlChannelCmd_CCmd_descriptor();
  }
  template<typename T>
  static inline const std::string& CCmd_Name(T enum_t_value) {
    static_assert(::std::is_same<T, CCmd>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function CCmd_Name.");
    return ControlChannelCmd_CCmd_Name(enum_t_value);
  }
  static inline bool CCmd_Parse(const std::string& name,
      CCmd* value) {
    return ControlChannelCmd_CCmd_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kControlChannelCmdFieldNumber = 1,
  };
  // .protocol.ControlChannelCmd.CCmd control_channel_cmd = 1;
  bool has_control_channel_cmd() const;
  private:
  bool _internal_has_control_channel_cmd() const;
  public:
  void clear_control_channel_cmd();
  ::protocol::ControlChannelCmd_CCmd control_channel_cmd() const;
  void set_control_channel_cmd(::protocol::ControlChannelCmd_CCmd value);
  private:
  ::protocol::ControlChannelCmd_CCmd _internal_control_channel_cmd() const;
  void _internal_set_control_channel_cmd(::protocol::ControlChannelCmd_CCmd value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.ControlChannelCmd)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  int control_channel_cmd_;
  friend struct ::TableStruct_protocol_2eproto;
};
// -------------------------------------------------------------------

class DataChannelCmd PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.DataChannelCmd) */ {
 public:
  inline DataChannelCmd() : DataChannelCmd(nullptr) {};
  virtual ~DataChannelCmd();

  DataChannelCmd(const DataChannelCmd& from);
  DataChannelCmd(DataChannelCmd&& from) noexcept
    : DataChannelCmd() {
    *this = ::std::move(from);
  }

  inline DataChannelCmd& operator=(const DataChannelCmd& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataChannelCmd& operator=(DataChannelCmd&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DataChannelCmd& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DataChannelCmd* internal_default_instance() {
    return reinterpret_cast<const DataChannelCmd*>(
               &_DataChannelCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DataChannelCmd& a, DataChannelCmd& b) {
    a.Swap(&b);
  }
  inline void Swap(DataChannelCmd* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DataChannelCmd* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DataChannelCmd* New() const final {
    return CreateMaybeMessage<DataChannelCmd>(nullptr);
  }

  DataChannelCmd* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DataChannelCmd>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DataChannelCmd& from);
  void MergeFrom(const DataChannelCmd& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataChannelCmd* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.DataChannelCmd";
  }
  protected:
  explicit DataChannelCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protocol_2eproto);
    return ::descriptor_table_protocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef DataChannelCmd_DCmd DCmd;
  static constexpr DCmd START_FORWARD_TCP =
    DataChannelCmd_DCmd_START_FORWARD_TCP;
  static constexpr DCmd START_FORWARD_UDP =
    DataChannelCmd_DCmd_START_FORWARD_UDP;
  static inline bool DCmd_IsValid(int value) {
    return DataChannelCmd_DCmd_IsValid(value);
  }
  static constexpr DCmd DCmd_MIN =
    DataChannelCmd_DCmd_DCmd_MIN;
  static constexpr DCmd DCmd_MAX =
    DataChannelCmd_DCmd_DCmd_MAX;
  static constexpr int DCmd_ARRAYSIZE =
    DataChannelCmd_DCmd_DCmd_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  DCmd_descriptor() {
    return DataChannelCmd_DCmd_descriptor();
  }
  template<typename T>
  static inline const std::string& DCmd_Name(T enum_t_value) {
    static_assert(::std::is_same<T, DCmd>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function DCmd_Name.");
    return DataChannelCmd_DCmd_Name(enum_t_value);
  }
  static inline bool DCmd_Parse(const std::string& name,
      DCmd* value) {
    return DataChannelCmd_DCmd_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kDataChannelCmdFieldNumber = 1,
  };
  // .protocol.DataChannelCmd.DCmd data_channel_cmd = 1;
  bool has_data_channel_cmd() const;
  private:
  bool _internal_has_data_channel_cmd() const;
  public:
  void clear_data_channel_cmd();
  ::protocol::DataChannelCmd_DCmd data_channel_cmd() const;
  void set_data_channel_cmd(::protocol::DataChannelCmd_DCmd value);
  private:
  ::protocol::DataChannelCmd_DCmd _internal_data_channel_cmd() const;
  void _internal_set_data_channel_cmd(::protocol::DataChannelCmd_DCmd value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.DataChannelCmd)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  int data_channel_cmd_;
  friend struct ::TableStruct_protocol_2eproto;
};
// -------------------------------------------------------------------

class Hello PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.Hello) */ {
 public:
  inline Hello() : Hello(nullptr) {};
  virtual ~Hello();

  Hello(const Hello& from);
  Hello(Hello&& from) noexcept
    : Hello() {
    *this = ::std::move(from);
  }

  inline Hello& operator=(const Hello& from) {
    CopyFrom(from);
    return *this;
  }
  inline Hello& operator=(Hello&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Hello& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Hello* internal_default_instance() {
    return reinterpret_cast<const Hello*>(
               &_Hello_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Hello& a, Hello& b) {
    a.Swap(&b);
  }
  inline void Swap(Hello* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Hello* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Hello* New() const final {
    return CreateMaybeMessage<Hello>(nullptr);
  }

  Hello* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Hello>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Hello& from);
  void MergeFrom(const Hello& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Hello* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.Hello";
  }
  protected:
  explicit Hello(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protocol_2eproto);
    return ::descriptor_table_protocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Hello_HelloType HelloType;
  static constexpr HelloType CONTROL_CHANNEL_HELLO =
    Hello_HelloType_CONTROL_CHANNEL_HELLO;
  static constexpr HelloType DATA_CHANNEL_HELLO =
    Hello_HelloType_DATA_CHANNEL_HELLO;
  static inline bool HelloType_IsValid(int value) {
    return Hello_HelloType_IsValid(value);
  }
  static constexpr HelloType HelloType_MIN =
    Hello_HelloType_HelloType_MIN;
  static constexpr HelloType HelloType_MAX =
    Hello_HelloType_HelloType_MAX;
  static constexpr int HelloType_ARRAYSIZE =
    Hello_HelloType_HelloType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  HelloType_descriptor() {
    return Hello_HelloType_descriptor();
  }
  template<typename T>
  static inline const std::string& HelloType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, HelloType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function HelloType_Name.");
    return Hello_HelloType_Name(enum_t_value);
  }
  static inline bool HelloType_Parse(const std::string& name,
      HelloType* value) {
    return Hello_HelloType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kHelloTypeFieldNumber = 1,
  };
  // .protocol.Hello.HelloType hello_type = 1;
  bool has_hello_type() const;
  private:
  bool _internal_has_hello_type() const;
  public:
  void clear_hello_type();
  ::protocol::Hello_HelloType hello_type() const;
  void set_hello_type(::protocol::Hello_HelloType value);
  private:
  ::protocol::Hello_HelloType _internal_hello_type() const;
  void _internal_set_hello_type(::protocol::Hello_HelloType value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.Hello)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  int hello_type_;
  friend struct ::TableStruct_protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ControlChannelCmd

// .protocol.ControlChannelCmd.CCmd control_channel_cmd = 1;
inline bool ControlChannelCmd::_internal_has_control_channel_cmd() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ControlChannelCmd::has_control_channel_cmd() const {
  return _internal_has_control_channel_cmd();
}
inline void ControlChannelCmd::clear_control_channel_cmd() {
  control_channel_cmd_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::protocol::ControlChannelCmd_CCmd ControlChannelCmd::_internal_control_channel_cmd() const {
  return static_cast< ::protocol::ControlChannelCmd_CCmd >(control_channel_cmd_);
}
inline ::protocol::ControlChannelCmd_CCmd ControlChannelCmd::control_channel_cmd() const {
  // @@protoc_insertion_point(field_get:protocol.ControlChannelCmd.control_channel_cmd)
  return _internal_control_channel_cmd();
}
inline void ControlChannelCmd::_internal_set_control_channel_cmd(::protocol::ControlChannelCmd_CCmd value) {
  _has_bits_[0] |= 0x00000001u;
  control_channel_cmd_ = value;
}
inline void ControlChannelCmd::set_control_channel_cmd(::protocol::ControlChannelCmd_CCmd value) {
  _internal_set_control_channel_cmd(value);
  // @@protoc_insertion_point(field_set:protocol.ControlChannelCmd.control_channel_cmd)
}

// -------------------------------------------------------------------

// DataChannelCmd

// .protocol.DataChannelCmd.DCmd data_channel_cmd = 1;
inline bool DataChannelCmd::_internal_has_data_channel_cmd() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool DataChannelCmd::has_data_channel_cmd() const {
  return _internal_has_data_channel_cmd();
}
inline void DataChannelCmd::clear_data_channel_cmd() {
  data_channel_cmd_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::protocol::DataChannelCmd_DCmd DataChannelCmd::_internal_data_channel_cmd() const {
  return static_cast< ::protocol::DataChannelCmd_DCmd >(data_channel_cmd_);
}
inline ::protocol::DataChannelCmd_DCmd DataChannelCmd::data_channel_cmd() const {
  // @@protoc_insertion_point(field_get:protocol.DataChannelCmd.data_channel_cmd)
  return _internal_data_channel_cmd();
}
inline void DataChannelCmd::_internal_set_data_channel_cmd(::protocol::DataChannelCmd_DCmd value) {
  _has_bits_[0] |= 0x00000001u;
  data_channel_cmd_ = value;
}
inline void DataChannelCmd::set_data_channel_cmd(::protocol::DataChannelCmd_DCmd value) {
  _internal_set_data_channel_cmd(value);
  // @@protoc_insertion_point(field_set:protocol.DataChannelCmd.data_channel_cmd)
}

// -------------------------------------------------------------------

// Hello

// .protocol.Hello.HelloType hello_type = 1;
inline bool Hello::_internal_has_hello_type() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Hello::has_hello_type() const {
  return _internal_has_hello_type();
}
inline void Hello::clear_hello_type() {
  hello_type_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::protocol::Hello_HelloType Hello::_internal_hello_type() const {
  return static_cast< ::protocol::Hello_HelloType >(hello_type_);
}
inline ::protocol::Hello_HelloType Hello::hello_type() const {
  // @@protoc_insertion_point(field_get:protocol.Hello.hello_type)
  return _internal_hello_type();
}
inline void Hello::_internal_set_hello_type(::protocol::Hello_HelloType value) {
  _has_bits_[0] |= 0x00000001u;
  hello_type_ = value;
}
inline void Hello::set_hello_type(::protocol::Hello_HelloType value) {
  _internal_set_hello_type(value);
  // @@protoc_insertion_point(field_set:protocol.Hello.hello_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::protocol::ControlChannelCmd_CCmd> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protocol::ControlChannelCmd_CCmd>() {
  return ::protocol::ControlChannelCmd_CCmd_descriptor();
}
template <> struct is_proto_enum< ::protocol::DataChannelCmd_DCmd> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protocol::DataChannelCmd_DCmd>() {
  return ::protocol::DataChannelCmd_DCmd_descriptor();
}
template <> struct is_proto_enum< ::protocol::Hello_HelloType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protocol::Hello_HelloType>() {
  return ::protocol::Hello_HelloType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2eproto
